### ISSUE TITLE
[BUG]插件“热重载”功能失效/The "Hot Reload" feature does not work properly.

### ISSUE THREAD

**Issue by CanynDream** [zerodegress/SFHR_ZModLoader#2]
### 问题描述/Issue Description

- 正确操作加载插件后，按“P”热重载贴图的功能无法生效，但BepInEx命令行窗口仍会正常提示对应信息。
After correctly loading the plugin, the hot reload texture feature does not work when pressing "P". However, the BepInEx command-line window still displays the corresponding information correctly.

### 游戏版本/Game Version

- v1.12

### 插件版本/Plugin Version

- 3.0.0 Release

**Comment by zerodegress** [comment]
问题已修复。
